### ISSUE TITLE
[Feature Request] ENDPOINT as Environment Variable

### ISSUE THREAD

**Issue by mitchellkellett** [GoodiesHQ/headscale-admin#17]
The readme says that you can change the endpoint if you build from the source, but it would be awesome if it were possible to set the endpoint from an env var rather than having to build it. If it's left blank, then it can default to /admin, but otherwise, I'd love to be able to set it myself.

**Comment by GoodiesHQ** [comment]
This was something I actually went back and forth on during initial development (deciding whether it would be a static or dynamic application). I ultimately decided on the former for its portability to any environment, and because the application itself is completely static, there is no program, service, or anything else to interpret environment variables. It's just HTML, CSS, and client-side JS files. The `ENDPOINT` as a build argument for the docker image is solely used at build time and the only thing it does is determines what the resulting `build` directory from `npm run build` will get renamed to at the end of the build process.

The docker container uses Caddy to serve the static directory. So `ENDPOINT` nothing inherent to the application, but it is `/admin` simply because, by default, the folder is renamed from `build` to `admin` and is thus accessible at `/admin`.

You have a couple of options and none of them are particularly great I think, but this is a limitation of the fact that the HTTP endpoint just mirrors the file system:
1) If you want, you could download the source code repo and make your own docker-compose.yml file which builds an image from that context and forwards an environment variable (I called it MY_ENDPOINT just to show the distinction from ENDPOINT, but I would call it the same thing, "ENDPOINT") as a build argument:

```
services:
  your_service_name:
    build:
      context: .
      args:
        ENDPOINT: ${MY_ENDPOINT}
```

2) In your container, you can rename the admin directory to whatever you'd like even after it is built. There is nothing baked into the application that references `/admin`, I chose it for two reasons: a) it's an endpoint that doesn't exist within headscale and b) if you click on the tailscale GUI and click on "admin console" it will open /admin on your headscale server.
