### ISSUE TITLE
Pass ENDPOINT as ENV var

### ISSUE THREAD

**Issue by Enissay** [GoodiesHQ/headscale-admin#37]
Would it be possible to pass the `ENDPOINT=/xyz` without the need to rebuild the image ?

The same is used in other similar HS UI: https://github.com/iFargle/headscale-webui/blob/main/docker-compose.yml which uses `SCRIPT_NAME=/admin` as ENV var

Checking the Dockerfile, it would be as simple as adding a single line to the dockerfile (assuming there's no other dependency): https://github.com/GoodiesHQ/headscale-admin/blob/e74547de6d3a7abf59bf837880ab3ea382e2433b/Dockerfile#L37-L39

```dockerfile
ARG ENDPOINT
ENV ENDPOINT=${ENDPOINT}    # <============= ADD
ARG PORT
ENV PORT=${PORT}
```

Since you had that already for PORT, I managed to overrite it to 9999 by adding the below to my docker compose:
```
    environment:
      PORT: "9999"
```

**Comment by GoodiesHQ** [comment]
Ah, I see the confusion. The ENDPOINT is received as an ENV during build time. This is because this determines the folder name that the build directory gets renamed to. That is all. It is not a runtime parameter, and therefore changing the environment variable in runtime does nothing. You have to rename the folder. If you want more control over it, you can also just take the admin folder, name it what you like, and host it as a static directory. Either that or rebuild the image with the build arg or env var ENDPOINT defined as what you'd like. The PORT on the other hand IS a runtime variable that can change between instances.

**Comment by Enissay** [comment]
Aha, I get it!
I hope there is a workaround to avoid rebuilding the image!
Or maybe publish 2 images, one with that forced endpoint, and the other without. Personally I use a subdomain, so I would like to get rid of that `/admin`.
Anyhow, thank you for the reply!
