### ISSUE TITLE
deploy page command missing.

### ISSUE THREAD

**Issue by thehoff** [GoodiesHQ/headscale-admin#4]
Deploy Page does not render the command/url box like the screenshots.
Tested in chrome and edge.
running latest docker image which is 0.1.4a

**Comment by GoodiesHQ** [comment]
Hi there! This was a bug introduced in that version because I changed the way the button on top was handled (and added a filtering section). In the Dev branch, I have added this back in properly and added preauth key selection on the deploy page. This will soon be version 0.1.5a and should be very close to the beta release.

**Comment by GoodiesHQ** [comment]
Should be solved in [v0.1.5a](https://github.com/GoodiesHQ/headscale-admin/tree/v0.1.5a). Docker :latest has been updated as well. Thanks!
